inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
